# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='profile.Profile'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='requested_friends',
            field=models.ManyToManyField(blank=True, related_name='requesting_friend', to='profile.Profile'),
        ),
    ]
